version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5001
      - REACT_APP_APPWRITE_ENDPOINT=${APPWRITE_ENDPOINT}
      - REACT_APP_APPWRITE_PROJECT_ID=${APPWRITE_PROJECT_ID}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - APPWRITE_ENDPOINT=${APPWRITE_ENDPOINT}
      - APPWRITE_PROJECT_ID=${APPWRITE_PROJECT_ID}
      - APPWRITE_API_KEY=${APPWRITE_API_KEY}
      - APPWRITE_DATABASE_ID=${APPWRITE_DATABASE_ID}
      - APPWRITE_COLLECTION_ID=${APPWRITE_COLLECTION_ID}
      - APPWRITE_IMAGE_BUCKET_ID=${APPWRITE_IMAGE_BUCKET_ID}
      - APPWRITE_ORDER_COLLECTION_ID=${APPWRITE_ORDER_COLLECTION_ID}
      - APPWRITE_USER_COLLECTION_ID=${APPWRITE_USER_COLLECTION_ID}